Add desktop version
Samuelwanza/portfolio_setup_and_mobile_first pull request #6
Opened 2023-05-04 21:15 UTC by Samuelwanza

-Refactored the index html to fit both mobile and desktop versions
-Styled the desktop version

2023-05-04 22:03 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @Samuelwanza 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-05-04 22:03 UTC, MaganaAsiati commented on index.html
> +      </div>
- Kindly make sure your card design stick as much as possible to the Figma design,  make sure that you reduce the space between the left and right sides of your card and add the height of your card and reduce the width to make it stick to the Figma. please check the comparison below :+1: 


## Figma design 

![image](https://user-images.githubusercontent.com/95297251/236339197-3e4edb89-2ef0-459b-bb77-5283dc113020.png)

## You design 


![image](https://user-images.githubusercontent.com/95297251/236336528-9d79bf61-dba2-4c53-8d5b-c803d7774d51.png)

2023-05-05 10:18 UTC, wayungi requested changes
Hi @Samuelwanza , 

![image](https://user-images.githubusercontent.com/99656687/234200054-89d3fce4-7f5b-4e07-a92f-9fad90948091.png)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- [ ] All linter checks passing ✔️ 
- [ ]  Correct GitHub flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 10:18 UTC, wayungi commented on index.html
>          </div>
- [ ] Your project cards are too small for the layout. Kindly increase their size to match the Figma. This change was requested by the previous reviewer but you have reduced them way too much. Kindly take guidance from the figma
 **figam**
 
![width1](https://user-images.githubusercontent.com/99656687/236431364-2282da2d-ab65-478e-9065-0b292272ac5d.png)

**Your design**
![width](https://user-images.githubusercontent.com/99656687/236431434-0b22a53e-a064-488c-b36c-b4b057204e7e.png)

2023-05-05 11:33 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYzJhZTk4ZWNlMjBkNjNhZDEzMjU1MDEwNmRmMjI2NDM4OTE5OTZiNCZjdD1n/WywjwXSThEWaZXAObk/giphy.gif)



# Hi @Samuelwanza 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- I'd advise you to double check the changes you make are in sync with the Figma design. You just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 11:33 UTC, AbelG101 commented on index.css
> +  }
- [ ] Please make sure the changes you introduce are aligned with the Figma design as I've noticed you're project images are stretching too much. see below 👇
  ![image](https://user-images.githubusercontent.com/104968236/236446251-42795a7c-b6f1-48a3-9c3f-31fad67d8a46.png)
- [ ] So in order to fix this issue you can start by removing the fixed heights you've set: 
    - [ ] 1st remove `height: 300px;` from the `.grid-item` class 
    - [ ] 2nd remove `height: 280px;` from the `.image-wrapper > img` selector at line `498`. 
    - [ ] Finally, you can make some other refinements in accordance 😉

2023-05-05 13:52 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 
Hi @Samuelwanza , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/E2UMcV4h2adHUm7Quz/giphy-downsized-medium.gif"/>

## Highlights
- All requested changes implemented :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 14:51 UTC, merged